wahlinfo/config/routes.rb
Wahlinfo::Application.routes.draw do

  get "mdb" => "mdb#index"
  get "mdb/:jahr" => "mdb#index"

  get "ueberhang/" => "ueberhang#index"
  get "ueberhang/:jahr" => "ueberhang#index"

  get "wahlkreissieger/"  => "wahlkreissieger#index"
  get "wahlkreissieger/:jahr"  => "wahlkreissieger#index"

  get "knapp/"  => "knapp#index"
  get "knapp/:jahr"  => "knapp#index"

  get "wkuebersicht/" => "wkuebersicht#index"
  get "wkuebersicht/:wk" => "wkuebersicht#index"

  match  "wahllokal/:action", :to => "wahllokal", via: [:get, :post]

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"

  get "vote/" => "vote#index"
  match  "vote/:action", :to => "vote", via: [:get, :post]

  resources :sessions

  get "/:jahr/" => "home#index"

 
  root 'home#index'

end

wahlinfo/app/models/erststimme.rb
class Erststimme < ActiveRecord::Base
  belongs_to :wahlkreis
  belongs_to :kandidat
  belongs_to :wahl
end

wahlinfo/app/models/kandidat.rb
class Kandidat < ActiveRecord::Base
  has_many :kandidaturs, dependent: :destroy
  has_many :stimmzettel, dependent: :restrict
end

wahlinfo/app/models/kandidatur.rb
class Kandidatur < ActiveRecord::Base
  belongs_to :wahl
  belongs_to :kandidat
  belongs_to :partei, :class_name => 'partei_landesliste'
  belongs_to :partei, :class_name => 'partei_direktkandidatur'
  belongs_to :partei, :class_name => 'partei_mitgliedschaft'
end

wahlinfo/app/models/land.rb
class Land < ActiveRecord::Base
  has_many :wahlkreises, dependent: :destroy
  has_many :wahlkreises, dependent: :restrict
end

wahlinfo/app/models/oberverteilung.rb
class Oberverteilung < ActiveRecord::Base
  self.table_name = "oberverteilung"
 
  belongs_to :partei

 
  
end

wahlinfo/app/models/partei.rb
class Partei < ActiveRecord::Base
end

wahlinfo/app/models/parteisitze.rb
class Oberverteilung < ActiveRecord::Base
  self.table_name = "oberverteilung"
 
  belongs_to :partei

 def to_s
    "Name:#{self.name} Age:#{self.age} Weight: #{self.weight}"
  end
  
end

wahlinfo/app/models/stimmrecht.rb
class Stimmrecht < ActiveRecord::Base
  belongs_to :wahllokal
end

=begin

class Stimmrecht < ActiveRecord::Base
  belongs_to :wahllokal

  attr_accessor :password

  before_save :encrypt_password

  def self.authenticate(password, wahllokal)
    stimmrecht = find(:conditions=>["password=? and project_id=?", params[:user_id], params[:project_id]])

    if wahllokal && wahllokal.password_hash == BCrypt::Engine.hash_secret(password, wahllokal.password_salt)
      wahllokal
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
    	self.password_salt = BCrypt::Engine.generate_salt
    	self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

end

=end

wahlinfo/app/models/wahl.rb
class Wahl < ActiveRecord::Base
  has_many :kandidaturs, dependent: :destroy
  has_many :stimmzettels, dependent: :destroy
end

wahlinfo/app/models/wahlkreis.rb
class Wahlkreis < ActiveRecord::Base
#  has_many :kandidaturs, dependent: :restrict
  belongs_to :land
end

wahlinfo/app/models/wahllokal.rb
class Wahllokal < ActiveRecord::Base
  belongs_to :wahlkreis

  attr_accessor :password

  before_save :encrypt_password
  after_save :clear_password


  validates_confirmation_of :password
  validates_presence_of :password, :on => :create

#   attr_accessible :wahlkreis, :wahlleiter, :adresse, :password, :password_confirmation


  def self.authenticate(id, password)
    wahllokal = find_by_id(id)
    if wahllokal && wahllokal.password_hash == BCrypt::Engine.hash_secret(password, wahllokal.password_salt)
      wahllokal
    else
      nil
    end
  end
  

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end


  def clear_password
    self.password = nil
  end

end

wahlinfo/app/models/wkinfo.rb
class Wkinfo < ActiveRecord::Base
   self.table_name = "wkinfo"

  belongs_to :partei, :class_name => 'partei_id'

 
  
end

wahlinfo/app/models/zweitstimme.rb
class Zweitstimme < ActiveRecord::Base
  belongs_to :wahlkreis
  belongs_to :partei
  belongs_to :wahl
end

wahlinfo/app/helpers/knapp_helper.rb
module KnappHelper
end

wahlinfo/app/helpers/mdb_helper.rb
module MdbHelper
end

wahlinfo/app/helpers/sessions_helper.rb
module SessionsHelper
end

wahlinfo/app/helpers/testing_helper.rb
module TestingHelper
end

wahlinfo/app/helpers/ueberhang_helper.rb
module UeberhangHelper
end

wahlinfo/app/helpers/vote_helper.rb
module VoteHelper
end

wahlinfo/app/helpers/welcome_helper.rb
module WelcomeHelper
end

wahlinfo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wahlinfo</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

        <meta name="description" content="">
        <meta name="author" content="ink, cookbook, recipes">
        <meta name="HandheldFriendly" content="True">
        <meta name="MobileOptimized" content="320">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
        <link rel="shortcut icon" href="../img/ink-favicon.ico">
        <link rel="apple-touch-icon-precomposed" href="../img/touch-icon.57.png">
        <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../img/touch-icon.72.png">
        <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../img/touch-icon.114.png">
        <link rel="apple-touch-startup-image" href="../img/splash.320x460.png"
        media="screen and (min-device-width: 200px) and (max-device-width: 320px) and (orientation:portrait)">
        <link rel="apple-touch-startup-image" href="../img/splash.768x1004.png"
        media="screen and (min-device-width: 481px) and (max-device-width: 1024px) and (orientation:portrait)">
        <link rel="apple-touch-startup-image" href="../img/splash.1024x748.png"
        media="screen and (min-device-width: 481px) and (max-device-width: 1024px) and (orientation:landscape)">
        <link rel="stylesheet" type="text/css" href="../css/ink.css">
        <!--[if IE 7 ]>
            <link rel="stylesheet" href="../css/ink-ie7.css" type="text/css" media="screen" title="no title" charset="utf-8">
        <![endif]-->
        
        <script type="text/javascript" src="../js/holder.js"></script>
        <script type="text/javascript" src="../js/ink.min.js"></script>
        <script type="text/javascript" src="../js/ink-ui.min.js"></script>
        <script type="text/javascript" src="../js/autoload.js"></script>
        <script type="text/javascript" src="../js/html5shiv.js"></script>
        
        
        <style type="text/css">
            html, body {
                height: 100%;
                background: #f0f0f0;
            }
            .wrap {
                min-height: 100%;
                height: auto !important;
                height: 100%;
                margin: 0 auto -80px;
                overflow: auto;
            }
            .push, footer { 
                height: 80px; 
                margin-top: 0; 
            }
            footer { 
                background: rgba(10,10,10,0.95); 
                border: 0; 
                line-height: 80px; 
                margin-top: 0 !important; 
            }
            footer * { 
                line-height: inherit; 
            }
            footer p { 
                margin-top: 0; 
            }
            footer .ink-navigation ul.menu.horizontal li { 
                margin-right: 2em; 
                line-height: inherit; 
            }
            footer .ink-navigation ul.menu.horizontal li a {
                padding: 0;
                color: white;
                text-decoration: underline;
            }
            footer p {
                color: white;
            }
            footer .ink-navigation ul.menu.horizontal li a:hover {
                color: #c91111;
            }
            .top-menu {
                background: #000;
            }
            .cta {
                font-size: 1.8em;
                margin-left: 0;
            }
        </style>    
    </head>
    <body>


    <div class="wrap">
      <div class="top-menu">
          <nav class="ink-navigation ink-grid">
              <ul class="menu horizontal black flat">

                <% if logged_in %>

                    <li><a class="logoPlaceholder"><u>Wahllokal: <%= logged_in.id %></u></a></li>

                    <% if manager %>
                        <li><a class="logoPlaceholder">Interface für den Wahlvorstand</li>
                        <li><%= link_to "Stimmrecht erteilen", '/wahllokal/stimmrecht' %></li>
                        <li><%= link_to "Log out", log_out_path %></li>
                    <% else %>
                      <li><%= link_to "Abstimmen",'/vote' %></li>  
                    <% end %>


                <% else %>

                      <li class=""><a href="/">Sitzverteilung</a>

                        <ul class="submenu">
                            <li><a href="/2009">2009</a></li>
                            <li><a href="/2013">2013</a></li>
                        </ul>
                    </li>

                      <li><%= link_to "Mitglieder des Bundestags",'/mdb' %>

                        <ul class="submenu">
                            <li><a href="/mdb/2009">2009</a></li>
                            <li><a href="/mdb/2013">2013</a></li>
                        </ul>
                    </li>

                      <li><%= link_to "Übersicht",'/wkuebersicht' %></li>  

                      <li><%= link_to "Wahlkreissieger",'/wahlkreissieger' %>

                      <ul class="submenu">
                            <li><a href="/wahlkreissieger/2009">2009</a></li>
                            <li><a href="/wahlkreissieger/2013">2013</a></li>
                        </ul>
                    </li>  

                      <li><%= link_to "Überhangmandate",'/ueberhang' %>

                        <ul class="submenu">
                            <li><a href="/ueberhang/2009">2009</a></li>
                            <li><a href="/ueberhang/2013">2013</a></li>
                        </ul>
                    </li>

                      <li><%= link_to "Knappste Sieger",'/knapp' %>
                        <ul class="submenu">
                            <li><a href="/knapp/2009">2009</a></li>
                            <li><a href="/knapp/2013">2013</a></li>
                        </ul>
                    </li>

                      <li><%= link_to "#",'/log_in' %>

                <% end %>
              </ul>
          </nav>
      </div>


      <div class="ink-grid vspace">

      <% if notice %>
        <p><span class="ink-label info">Hinweis:</span> <%= notice %></p>
      <% end %>

        <%= yield %>

      </div>


        <div class="push"></div>  
      </div>

        <footer>
        <div class="ink-grid">
            <nav class="ink-navigation push-left medium-100 small-100 small-push-left">
                <!-- <ul class="menu horizontal">
                    <li class="active"><li><%= link_to "2013", '/2013' %></li>
                    <li><%= link_to "2009", params[:controller] + '/2009' %></li>
                </ul> -->
            </nav>
            <p class="push-right small-100">© Felix Jankowski, Maria Meier, 2013-2014</p>
        </div>
        </footer>
    </body>
</html>